name: FRONT – Stage Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'shopping-lister-front/**'

jobs:
  test_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: npm ci
        working-directory: ./shopping-lister-front
      - name: Format code and check for errors
        run: npm run lint:full
        working-directory: ./shopping-lister-front
      - name: Run tests
        run: npm run test:unit
        working-directory: ./shopping-lister-front
      - name: Build project
        run: npm run build
        working-directory: ./shopping-lister-front
      - name: Deploy
        run: |
          mkdir -p ~/shopping-lister-front-stage
          cp -a . ~/shopping-lister-front-stage/
          cd ~/shopping-lister-front-stage
          npm install -g pm2
          pm2 start npm --name "shopping-lister-front-stage" -- preview
        working-directory: ./shopping-lister-front
